language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
  yarn: true
before_script:
  - npm i
script:
  - npm run build
after_success:
  - if [ ${TRAVIS_BRANCH} = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ];then
    npm run publish;
    fi
